name: License Compliance Verification

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  issues: read
  checks: write

jobs:
  license-compliance-verification:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          gradle-version: '8.5'

            # Install License Finder using Homebrew
      - name: Install License Finder
        run: |
          # Install Homebrew
          sudo apt update
          sudo apt install -y build-essential curl
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          
          # Install license_finder using brew
          brew install license_finder

           # Install License Finder using Homebrew
      - name: Install License Finder
        run: |
          # Install Homebrew
          sudo apt update
          sudo apt install -y build-essential curl
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
          
          # Add Homebrew to the PATH
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          
          # Install licensefinder using Homebrew
          brew install licensefinder

      # Run License Finder
      - name: 'Run License Finder'
        run: |
          licensefinder report --format xml --output-file license_finder_report.xml


      # Upload Report In Artifact
      - name: 'Upload Dependency Review Report In Artifact'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml
