name: License Compliance Check

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
  # Run weekly at midnight on Sunday

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  packages: write

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set permissions for gradlew
      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 
        with:
          gradle-version: 8.5  

      # Build the project
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Run License Compliance Check
        run: ./gradlew generateLicenseReport
        continue-on-error: true

      - name: Upload License Compliance Report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: build/reports/dependency-license.json

      - name: Fail if License Compliance Issues Found
        run: |
          if grep -q "UNLICENSED" build/reports/dependency-license.json; then
            echo "License compliance issues found!"
            exit 1
          fi
