name: License Compliance Verification
 
on:
  push:
    branches: [ "main" ]
 
permissions:
  contents: read
  issues: read
  checks: write
 
jobs:
  license-compliance-verification:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      
      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      
      # Generate License Report
      - name: Generate License Report
        run: ./gradlew generateLicenseReport
        
      # Convert License Report to XML
      - name: Convert License Report to XML
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <testsuites>
            <testsuite name="License Compliance" tests="1">
          ' > license_finder_report.xml
          
          if [ -f "build/reports/dependency-license/licenses.json" ]; then
            echo '<testcase name="License Check" status="passed"/>' >> license_finder_report.xml
          else
            echo '<testcase name="License Check" status="failed">
              <failure message="License check failed"/>
            </testcase>' >> license_finder_report.xml
          fi
          
          echo '  </testsuite>
          </testsuites>' >> license_finder_report.xml
 
      # Publish Report to GitHub UI
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        if: always()
        with:
          junit_files: "license_finder_report.xml"
 
      # Upload License Report as Artifact
      - name: Upload License Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-reports
          path: |
            build/reports/dependency-license/*
            license_finder_report.xml