name: License Compliance Verification

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  issues: read
  checks: write

jobs:
  license-compliance-verification:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # Install Dependencies for License Finder (if needed)
      - name: 'Install License Finder'
        run: |
          apt-get update
          apt-get install -y ruby
          gem install --user-install license_finder
        env:
          PATH: "${HOME}/.gem/ruby/3.0.0/bin:${PATH}"


      # Run License Finder with Gradle
      - name: 'Run License Finder'
        run: |
          ./gradlew dependencies --configuration runtimeClasspath > dependencies.txt
          license_finder report --enabled-package-managers=gradle --format xml --quiet --decisions-file=decisions.yml --output-file=license_finder_report.xml

      # Publish Report to GitHub UI
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        if: always()
        with:
          junit_files: "license_finder_report.xml"

      # Upload Report In Artifact
      - name: 'Upload Dependency Review Report In Artifact'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml
